FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY pyproject.toml .
COPY uv.lock .

RUN uv pip install --system .
RUN uv pip install --system "sentence-transformers>=3.0.0"

COPY . .

CMD ["python", "-m", "src.worker.main"]
